#!/bin/bash
cd "../ainojs-$1"
if [ "$2" != "-f" ] && git diff-index --quiet HEAD --; then
    echo "No changes to $1, build canceled"
else
  echo "$1 has changed, building minor"
  cd "../ainojs-build"
  eval "./node_modules/.bin/gulp $1-minor"
  cd "../ainojs-$1"
  VERSION=$(git describe --tags)
  git add .
  eval "git commit -am 'Building minor from version $VERSION'"
  npm version minor
  git push origin master
  git push --tags
  npm publish
fi