#!/bin/bash
cd "../ainojs-$1"
if git diff-index --quiet HEAD --; then
    echo "No changes to $1, build canceled"
else
  echo "$1 has changed, building patch"
  cd "../ainojs-build"
  eval "./node_modules/.bin/gulp $1-patch"
  cd "../ainojs-$1"
  VERSION=$(git describe --tags)
  git add .
  eval "git commit -am 'Building patch from version $VERSION'"
  npm version patch
  git push origin master
  git push --tags
  npm publish
fi